version: 2

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

runner:
  skip-dirs:
    - vendor
    - testdata
    - .git

  skip-files:
    - ".*/go/.*"
    - ".*/src/.*"

issues:
  exclude-rules:
    - path: ".*/go/.*"
      linters: ["*"]
    - path: '_test\.go'
      linters:
        - errcheck
