name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '~1.22.0'
        check-latest: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race ./...

  code-quality:
    runs-on: ubuntu-latest
    needs: build  # Wait for build job to complete
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.57.2
        working-directory: ./
        args: >
          --timeout=5m
          --out-format=github-actions

  push:
    runs-on: ubuntu-latest
    needs: [build, code-quality]  # Requires both jobs to succeed
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}
          ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: push  # Wait for push job to complete
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Update Helm chart
      run: |
        yq eval -i '.image.tag = "${{github.run_id}}"' helm/go-web-app-chart/values.yaml
        
    - name: Commit changes
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "CI: Update image tag to ${{ github.run_id }}"
        git push